### ISSUE TITLE
Vertuo  update

### ISSUE THREAD

**Issue by DEEJCUK** [atdr/capsule-caffeine#3]
Hello, I thought it would be easy to just add the vertuo  link to the a scraper but it gives an error which I don’t understand, is there any chance of the scraper and Apple shortcut being updated to Include vertuo ?

**Comment by atdr** [comment]
Thanks @DEEJCUK, it looks like Vertuo pod pages do still have the relevant information on them (e.g., <https://www.nespresso.com/tw/en/order/capsules/vertuo/melozio-vertuo-coffee-pods>) so should be possible to modify the scraper to extract this

**Comment by DEEJCUK** [comment]
I see the shortcut contains the ones I was looking for, thanks
